# ----------------------------------------------------------------------------
#
# Package             : tblib
# Source Repo         : https://github.com/ionelmc/python-tblib
# Travis Job Link     : https://travis-ci.com/github/santosh653/pylibdmtx
# Created travis.yml  : No
# Maintainer          : Santosh Kulkarni <santoshkulkarni70@gmail.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: xenial
cache: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - LD_PRELOAD=/lib/powerpc64le-linux-gnu/ld-2.31.so
    - SEGFAULT_SIGNALS=all
    
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=check
      arch: amd64
    - env:
        - TOXENV=py27,codecov
      python: '2.7'
      arch: amd64
    - env:
        - TOXENV=py35,codecov
      python: '3.5'
      arch: amd64
    - env:
        - TOXENV=py36,codecov
      python: '3.6'
      arch: amd64
    - env:
        - TOXENV=py37,codecov
      python: '3.7'
      arch: amd64
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
      arch: amd64
    - env:
        - TOXENV=pypy,codecov
      python: 'pypy'
      arch: amd64
    - env:
        - TOXENV=pypy3,codecov
        - TOXPYTHON=pypy3
      python: 'pypy3'
      arch: amd64   
    
    - python: '3.6'
      env:
        - TOXENV=check
      arch: ppc64le
    - env:
        - TOXENV=py27,codecov
      python: '2.7'
      arch: ppc64le
    - env:
        - TOXENV=py35,codecov
      python: '3.5'
      arch: ppc64le
    - env:
        - TOXENV=py36,codecov
      python: '3.6'
      arch: ppc64le
    - env:
        - TOXENV=py37,codecov
      python: '3.7'
      arch: ppc64le
    - env:
        - TOXENV=py38,codecov
      python: '3.8'
      arch: ppc64le

before_install:
  - python --version
  - uname -a
  - lsb_release -a || true
install:
  - python -mpip install --progress-bar=off tox -rci/requirements.txt
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: never
    on_failure: always
